---
title: "rec_system"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(janitor)
```


## Loading Data


```{r, message=FALSE}
# url = "https://files.grouplens.org/datasets/movielens/ml-latest-small.zip"
# download.file(url, destfile = "data.zip")
# dir.create("data")
# unzip("data.zip",exdir = "data")   

links <- read_csv("data/ml-latest-small/links.csv") %>% 
  clean_names()

movies <- read_csv("data/ml-latest-small/movies.csv") %>% 
  clean_names()

ratings <- read_csv("data/ml-latest-small/ratings.csv") %>% 
  clean_names()

tags <- read_csv("data/ml-latest-small/tags.csv") %>% 
  clean_names()
```


```{r}
movies2 <- movies %>% 
  separate_rows(genres, sep = "\\|")
```


```{r}
ratings %>% 
  ggplot(aes(x = rating)) +
  geom_bar() +
  theme_bw()
```



```{r}
ratings <- ratings %>% 
  filter(rating != "0")
```


```{r}
ratings_cnt <- ratings %>% 
  group_by(user_id) %>% 
  count()

summary(ratings_cnt$n)
```


```{r}
ratings <- ratings %>% 
  group_by(user_id) %>% 
  filter(n() >= 169)

# Calculating the avg rating for each movie
movies2 <- movies2 %>% 
  filter(movie_id %in% ratings$movie_id) %>% 
  group_by(movie_id) %>% 
  slice(1)
```


```{r}
movies_rating <- ratings %>% 
  group_by(movie_id) %>% 
  summarise(movie_rating = mean(rating)) %>% 
  inner_join(
    movies2,
    by = c("movie_id" = "movie_id")
  )
```


```{r}
# filtering out the top 1000 most popularly rated movies
ratings_cnt <- ratings %>% 
  group_by(movie_id) %>% 
  summarise(ratings_cnt = n()) %>% 
  arrange(desc(ratings_cnt))

movies_rating <- movies_rating %>% 
  filter(movie_id %in% ratings_cnt$movie_id[1:1000])

# rearranging columns
movies_rating <- movies_rating %>% 
  select(movie_id, title, genres, movie_rating)
```



## Content-Based Recommendation System

```{r}
library(cluster)
```


```{r}
movies_rating <- movies_rating %>% 
  left_join(
    tags,
    by = c("movie_id" = "movie_id")
  ) %>% 
  select(-c(user_id, timestamp)) %>% 
  group_by(movie_id) %>% 
  slice(1)

movies_rating <- movies_rating %>% 
  mutate(
    movie_id = paste0("movie_", movie_id)
  ) 

movies_feature <- movies_rating %>% 
  ungroup() %>% 
  select(genres, movie_rating, tag) %>% 
  mutate(
    genres = as.factor(genres),
    tag = as.factor(tag)
  )
```


```{r}
movie_dissimilarity <- daisy(
  movies_feature,
  metric = "gower",
  weights = c(2, 1, 0.5)
)

movie_dissimilarity <- as.matrix(movie_dissimilarity)

colnames(movie_dissimilarity) <- movies_rating$movie_id
rownames(movie_dissimilarity) <- movies_rating$movie_id
```


```{r}
# selecting movies for one particular user
ratings <- ratings %>% 
  group_by(user_id) %>% 
  mutate(
    user_id = paste0("user_", user_id),
    movie_id = paste0("movie_", movie_id)
  ) %>% 
  ungroup()

# set.seed(1234)
# user <- paste0("user_", sample(length(unique(ratings$user_id)), 1))
user <- "user_28"

user_movies <- ratings %>% 
  filter(
    user_id == user,
    movie_id %in% movies_rating$movie_id
  )
```



```{r}
selected_movies <- user_movies %>% 
  select(movie_id, rating)
```


```{r}
recommender <- function(
    selected_movies, dis_matrix, movies, n_recommendations = 5
) {
  movie_indices <- which(colnames(dis_matrix) %in% selected_movies$movie_id)
  
  results <- data.frame(
    dis_matrix[, movie_indices],
    recommended_movie = rownames(dis_matrix),
    stringsAsFactors = FALSE
  )
  
  recommendations <- results %>% 
    pivot_longer(
      cols = -c("recommended_movie"),
      names_to = "watched_movie",
      values_to = "dissimilarity"
    ) %>% 
    left_join(
      selected_movies,
      by = c("recommended_movie" = "movie_id") 
    ) %>% 
    arrange(desc(dissimilarity)) %>% 
    filter(recommended_movie != watched_movie) %>% 
    filter(!is.na(rating)) %>% 
    mutate(
      similarity = 1 - dissimilarity,
      weighted_score = similarity * rating) %>%
    arrange(desc(weighted_score)) %>%
    filter(weighted_score > 0) %>%
    group_by(recommended_movie) %>% 
    slice(1) %>%
    top_n(n_recommendations, weighted_score)  %>%
    left_join(movies_rating, by = c("recommended_movie" = "movie_id"))

  return(recommendations)
}
```


```{r}
recs <- recommender(selected_movies, movie_dissimilarity, movies_rating)
```
































